const wordList = [
    { word: "manzana", hint: "Comestible, de forma redondeada y algo hundida por los extremos, piel fina, de color verde, amarillo o rojo."},
    { word: "ovoviviparo", hint: "Se aplica a los animales cuyos embriones se desarrollan totalmente en el huevo que está en el interior del cuerpo de la madre."},
    { word: "oxigeno", hint: "Elemento químico gaseoso, incoloro, inodoro e insípido, que constituye una quinta parte del aire atmosférico."},
    { word: "pantano", hint: "Terreno bajo y cenagoso, cubierto de agua, que no es muy honda."},
    { word: "paralelepipedo", hint: "Cuerpo geométrico limitado por seis paralelogramos."},
    { word: "ardilla", hint: "Pequeño mamífero roedor de cola larga y peluda." },
    { word: "esmeralda", hint: "Gema verde preciosa." },
    { word: "galaxia", hint: "Conjunto enorme de estrellas, polvo interestelar y gas." },
    { word: "orquidea", hint: "Planta con flores exquisitas y complejas." },
    { word: "paraguas", hint: "Objeto que protege de la lluvia." },
    { word: "murcielago", hint: "Mamífero volador nocturno." },
    { word: "calabaza", hint: "Fruta de piel dura y pulpa comestible." },
    { word: "quimera", hint: "Criatura mitológica con partes de varios animales." },
    { word: "serenidad", hint: "Tranquilidad y paz interior." },
    { word: "nebulosa", hint: "Región interestelar de gas y polvo." },
    { word: "anticonstitucionalidad", hint: "Contrario a lo establecido en la Constitución." },
    { word: "inconmensurabilidad", hint: "Imposibilidad de ser comparado o medido con exactitud." },
    { word: "hipopotomonstrosesquipedaliofobia", hint: "Miedo irracional a las palabras largas." },
    { word: "sesquipedalidad", hint: "Cualidad de ser largo o prolijo en la expresión." },
    { word: "supercalifragilisticoespialidoso", hint: "Palabra inventada famosa por Mary Poppins." },
    { word: "espectrofotometria", hint: "Medición de la intensidad de la luz absorbida o emitida por una sustancia." },
    { word: "circunlocucion", hint: "Manera indirecta de expresar una idea." },
    { word: "intrincado", hint: "Complicado, enmarañado, de difícil comprensión." },
    { word: "anacronismo", hint: "Error que consiste en situar algo fuera de su tiempo histórico." },
    { word: "perplejidad", hint: "Estado de confusión o indecisión." },
    { word: "efervescente", hint: "Que desprende burbujas de gas." },
    { word: "inefable", hint: "Que no puede ser expresado con palabras." },
    { word: "ultracrepidariano", hint: "Que da opiniones sobre algo fuera de su competencia." },
    { word: "polimatia", hint: "Conocimiento enciclopédico." },
    { word: "efimero", hint: "De corta duración o vida breve." },
    { word: "anomalo", hint: "Que se aparta de lo común o sigue una norma inusual." },
    { word: "disparate", hint: "Dicho o hecho absurdo que carece de lógica." },
    { word: "sinécdoque", hint: "Figura retórica que consiste en designar la parte por el todo." },
    { word: "anarquía", hint: "Ausencia de gobierno o autoridad." },
    { word: "apocope", hint: "Supresión de una letra o sílaba al final de una palabra." },
    { word: "karma", hint: "Concepto hinduista y budista que expresa la ley de causa y efecto." },
    { word: "quirúrgico", hint: "Relacionado con la cirugía o propio de ella." },
    { word: "perpendicular", hint: "Que forma un ángulo recto con algo." },
    { word: "moribundo", hint: "Que está próximo a morir o que está en un estado de debilidad extrema." },
    { word: "opera", hint: "Género de música teatral en el que los personajes cantan sus partes." },
    { word: "xilofono", hint: "Instrumento musical de percusión con láminas de madera." },
    { word: "zafarrancho", hint: "Desorden o confusión." },
    { word: "sintaxis", hint: "Conjunto de reglas y principios que rigen la estructura de las oraciones en un lenguaje, especialmente en gramática." },
    { word: "gravedad", hint: "Fuerza que atrae dos masas entre sí." },
    { word: "termodinamica", hint: "Estudio de la relación entre el calor y otras formas de energía." },
    { word: "potencia", hint: "Rapidez con la que se realiza trabajo." },
    { word: "metafisica", hint: "Rama de la filosofía que trata de los principios y fundamentos de la realidad." },
    { word: "universal", hint: "Lo que es común a todos los individuos de una especie." },
    { word: "foton", hint: "Partícula elemental de luz." },
    { word: "cosmos", hint: "Todas las cosas que existen, incluido el espacio y todo lo que contiene." },
    { word: "oasis", hint: "Área fértil en un desierto con agua y vegetación." },
    { word: "melodia", hint: "Secuencia de sonidos armoniosos." },
    { word: "aventura", hint: "Experiencia emocionante o arriesgada." },
    { word: "tecnologia", hint: "Conjunto de conocimientos y técnicas aplicadas a la producción y desarrollo de bienes y servicios." },
]
